[config]
    [mysql]
        addr = "127.0.0.1:3306"
        user = "root"
        pass = "root"
        DB = "wallbbs"
        connect_timeout = 86400
    [redis]
        addr = "127.0.0.1"
        port = "6379"
        pass = ""
        dbid = 1
    [httpengine]
        port = "127.0.0.1:8083"
